In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
np. __version__

'1.20.3'

In [12]:
x=np.zeros(5, dtype="int")

In [13]:
x

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.empty((6,6))

array([[4.67296746e-307, 1.69121096e-306, 1.37961438e-306,
        1.42419938e-306, 7.56603881e-307, 8.45603440e-307],
       [3.11510340e-307, 3.33774490e-307, 4.89544090e-307,
        6.23041391e-307, 3.44900369e-307, 3.22646744e-307],
       [1.74005889e-312, 2.00269549e-307, 2.33645487e-307,
        1.29058426e-306, 1.24612081e-306, 8.62236067e-308],
       [1.42420481e-306, 1.24612013e-306, 1.11260144e-306,
        1.33511562e-306, 7.56591658e-307, 1.33511290e-306],
       [1.33511562e-306, 9.34605716e-307, 3.22650139e-307,
        6.89800737e-307, 3.56044072e-307, 2.33644129e-307],
       [4.00540117e-307, 1.00132483e-307, 2.33645997e-307,
        4.89541034e-307, 1.44635488e-307, 9.34609111e-307]])

In [22]:
list=[12,22,33,44,55]

In [27]:
list1=np.array(list)

In [29]:
list1

array([12, 22, 33, 44, 55])

In [28]:
np.arange(10,100,5) #start, stop, step

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [30]:
list1.shape

(5,)

In [31]:
list1.size

5

In [40]:
#0D Array
array0=np.array(5)

In [41]:
array0

array(5)

In [42]:
arr1=np.array([1,2,3,4,5]) #1D array

In [43]:
arr1

array([1, 2, 3, 4, 5])

In [44]:
arr2=np.array([[22,33,44,55,66,77]])

In [45]:
arr2

array([[22, 33, 44, 55, 66, 77]])

In [47]:
arr3=np.array([[[11,22,33,44,55,66,77,88,99]]])

In [48]:
arr3

array([[[11, 22, 33, 44, 55, 66, 77, 88, 99]]])

# Another Method to create arrays

In [50]:
arr2d=np.arange(20).reshape(5,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
arr3d=np.arange(30).reshape(10,3)
arr3d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [53]:
arr3d.dtype

dtype('int32')

In [54]:
arr3d.ndim

2

# Random Number numpy

In [72]:
from  numpy import random
x=random.randint(10)  #it will generate integer random number within the value of 10

In [73]:
x

5

In [74]:
y=random.randint(100)
y

50

In [80]:
z=random.rand()
z             #it will geberate float random numbers

0.05287696777124895

# creating array from Random  numbers

In [91]:
r=random.randint(10, size=([1,2,3]))

In [92]:
r

array([[[3, 7, 5],
        [4, 7, 8]]])

In [96]:
rr=random.rand(20)

In [97]:
rr

array([0.64943237, 0.07932775, 0.15216785, 0.53043533, 0.72225424,
       0.17682166, 0.078841  , 0.7556363 , 0.91493521, 0.85106435,
       0.08557363, 0.82194458, 0.02384198, 0.92278101, 0.43927515,
       0.95074704, 0.75407022, 0.34721959, 0.66280284, 0.8786762 ])

In [118]:
x=random.choice([1,2,3,4])  #it will extract randomly any number from the given array

In [119]:
x

1

In [121]:
mylist=(["Farhan","daud","minhal"])
shuffle=random.shuffle(mylist)               #it will shuffle the elemnt from my given array


In [122]:
shuffle

In [129]:
mylist

['minhal', 'Farhan', 'daud']

In [132]:
per=random.permutation(mylist)   #permutation are same as shuffle

In [133]:
mylist

['minhal', 'Farhan', 'daud']

# Indexing 

In [134]:
ind=np.array([1,2,3,4,5,6])

In [135]:
ind

array([1, 2, 3, 4, 5, 6])

In [136]:
ind[1]

2

In [137]:
ind[2]

3

In [138]:
ind[3]

4

In [139]:
ind[0]

1

# Boolean indexing

In [140]:
ind[x>4]

array([], shape=(0, 6), dtype=int32)

# fancy indexing

In [142]:
ind[[2,3]]  #it will return multiple values by indexing number that is we give 

array([3, 4])

In [148]:
x=random.randint(10)

In [149]:
x

0

# Slicing

In [150]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [151]:
arr[1:3]

array([2, 3])

In [152]:
arr[0:3]

array([1, 2, 3])

In [153]:
arr[4:]

array([5, 6, 7])

In [154]:
arr[ : 3]

array([1, 2, 3])

# Negative Slicing

In [163]:
arr=np.array([1,2,3,4,5,6])

In [166]:
array[-1:-4:-1]

[6, 5, 4]

In [167]:
arr2d=np.arange(20).reshape(5,4)

In [168]:
arr2d


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [171]:
arr2d[0][3]

3

In [172]:
arr2d[0]

array([0, 1, 2, 3])

In [173]:
arr1d=np.array([1,2,3,4,5,6])

In [174]:
arr1d

array([1, 2, 3, 4, 5, 6])

In [175]:
arr1d[1:3]

array([2, 3])

In [177]:
arr1d[-1:-3:-1]

array([6, 5])

In [178]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [179]:
arr2d[3:5,0:2]

array([[12, 13],
       [16, 17]])

In [187]:
arr1=([1,2,3,4])
x=arr1.copy()
arr1[0]=42

print(arr1)
print(x)

[42, 2, 3, 4]
[1, 2, 3, 4]


In [188]:
array=([1,2,3,3,4,5,66,66])

In [189]:
array

[1, 2, 3, 3, 4, 5, 66, 66]

In [190]:
x=array.copy()
array[3]=4

In [191]:
print(array)
print(x)

[1, 2, 3, 4, 4, 5, 66, 66]
[1, 2, 3, 3, 4, 5, 66, 66]


# view

In [192]:
array=np.array([1,2,3,4])

In [193]:
array

array([1, 2, 3, 4])

In [194]:
y=array.view()
array[1]=1
print(array)
print(y)

[1 1 3 4]
[1 1 3 4]


In [195]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [196]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
