# Numpy basically an arry

In [1]:
import numpy as np

In [2]:
x = np.array([22,33,44,55])

In [3]:
x.size

4

In [4]:
x.shape

(4,)

In [6]:
x.ndim

1

In [7]:
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# now we will create 2d array

In [8]:
arr2d=np.array([[1,2,3],[11,22,33],[111,222,333]])

In [9]:
arr2d.shape

(3, 3)

In [10]:
arr2d.size

9

In [11]:
arr2d=np.arange(20).reshape(1,20)

In [12]:
arr2d=np.arange(20).reshape(4,5)

In [13]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
arr2d.shape

(4, 5)

In [15]:
arr2d.ndim

2

In [16]:
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
arr2d.shape

(4, 5)